# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0abe38fd9c85e8a19b9b266e8488339fde4369d571c960f411a00f241f8598c591f3ae2d8864bde284c3c7a27a85fc6e3bf06c460d1f57e45b37f69198385035

test:
  secret_key_base: 8da70c6b94d90ca86e01a93a02fe62de70b4133f000303a9fd95b53d74324bab238e5880d898ee661e8652f2092d9d9f59068022ffa3774b656c9c786fbd9978

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
